# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: university_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: 'postgres'
      POSTGRES_USER: 'db_user'
      POSTGRES_PASSWORD: '112233ee'
      POSTGRES_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - 5432:5432
    networks:
      - university_system_network
  university:
    container_name: university
    image: university:latest
    ports:
      - 8080:8080
    networks:
      - university_system_network
networks:
  university_system_network:
    external: true
    driver: bridge
