spring:
  datasource:
    username: 'db_user'
    password: '112233ee'
    url: 'jdbc:postgresql://university_db:5432/postgres'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher